.TH QUOTACHECK 8
.SH NAME
quotacheck \- scan a filesystem for disk usages
.SH SYNOPSIS
.B quotacheck
[-g] [-u] [-v] -a
.br
.B quotacheck
[-g] [-u] [-v] filesys ...
.SH DESCRIPTION
.I Quotacheck
performs a filesystems scan for usage of files and directories, used
by either user or group.
XFS filesystems are ignored by
.IR quotacheck ,
since the XFS quota system is journaled and therefore inherently consistent.
.PP
The output is the quota file for the corresponding filesystem.
By default the names for these files are:
.br
\-  A user scan: 
.I quota.user 
.br
\-  A group scan:
.I quota.group 
.PP
The resulting file consists of a
.I struct dqblk
for each possible id up to the highest existing uid or gid and contains the
values for the disk file and block usage and possibly excess time for these
values. ( for definitions of
.I struct dqblk
see
.I \<linux/quota.h\>
)
.PP
.I Quotacheck
should be run each time the system boots and mounts non-valid filesystems.
This is most likely to happen after a system crash.
.PP
The speed of the scan decreases with the number of directories increasing.
The time needed doubles when disk usage is doubled as well. A 100 MB partition
used for 94% is scanned in 1 minute, the same partition used for 50% is
done in 25 seconds.
.SH OPTIONS
.TP
.B \-v
This way the program will give some useful information about what it is
doing, plus some fancy stuff.
.TP
.B \-d
This means debug. It will result in a lot of information which can be used
in debugging the program. The output is very verbose and the scan
will not be fast.
.TP
.B \-u
This flag tells the program to scan the disk and to count the files and
directories used by a certain uid. This is the default action.
.TP
.B \-g
This flag forces the program to count the files and directories
used by a certain gid.
.TP
.B \-a
Check all of the quotas for the filesystems mentioned in /etc/mtab. Both
user and group quotas are checked as indicated by the /etc/mtab options.
.TP
.B \-R
When used in conjunction with \fP\-a\fR, all filesystems except the root 
filesystem are checked for quotas.
.SH NOTE
.I Quotacheck
should only be run as Super User. Non-privilidged users are presumably not allowed
to read all the directories on the given filesystem.
.SH "SEE ALSO"
quota(1), quotactl(2), fstab(5), quotaon(8), quotaoff(8), edquota(8), 
repquota(8), fsck(8)
.SH FILES
.PD 0
.TP 20
.B aquota.user or aquota.group
quota file at the filesystem root (version 2 quota, non-XFS filesystems)
.TP 20
.B quota.user or quota.group
quota file at the filesystem root (version 1 quota, non-XFS filesystems)
.TP
.B /etc/mtab
default filesystems
.PD
.SH "AUTHOR"
Edvard Tuinder \<ed@elm.net\>
.br
Marco van Wieringen \<mvw@planets.elm.net\>

